app = "<YOUR APP NAME GOES HERE>"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "grafana/grafana:8.0.2"

[mount]
  source = "grafana_storage"
  destination = "/var/lib/grafana"

[env]
  GF_SECURITY_ADMIN_PASSWORD = "<YOUR GRAFANA ADMIN PASSWORD GOES HERE>"
  GF_USERS_ALLOW_SIGN_UP = false
  GF_INSTALL_PLUGINS = "grafana-worldmap-panel,grafana-clock-panel"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 3
    timeout = "5s"
